networks:
    default:
        name: llm-rag-network
        external: true
services:
    llm-rag-cli:
        image: llm-rag-cli
        container_name: llm-rag-cli
        privileged: true  # Enable privileged mode for gcs fuse
        cap_add:
            - SYS_ADMIN      # Add SYS_ADMIN capability
        devices:
            - /dev/fuse     # Allow access to /dev/fuse
        volumes:
            - ../secrets:/secrets
            - ../datapipeline:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GOOGLE_APPLICATION_CREDENTIALS_data: $GOOGLE_APPLICATION_CREDENTIALS_data
            GCP_PROJECT: $GCP_PROJECT
            GCS_BUKCET_NAME: $GCS_BUCKET_NAME $IMAGE_NAME
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:0.5.5
        container_name: llm-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
