networks:
    default:
        name: llm-rag-network
        external: true
services:
    test-image:
        image: test-image
        container_name: test-image-container
        depends_on:
            - chromadb
        command: ["tail", "-f", "/dev/null"]
        volumes:
            - .:/app:delegated
            - ./coverage:/app/coverage:delegated
        environment:
            - COVERAGE_FILE=/app/coverage/.coverage
            - PYTHONPATH=/app/src
        user: "${UID:-1000}:${GID:-1000}"
    chromadb:
        image: chromadb/chroma:0.5.5
        container_name: llm-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]