name: Run Tests
on:
  push:
    branches: [ milestone4, tests ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 
    
      - name: Run flake8
        run: |
          flake8 --ignore=E501,E402 src/
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
      - name: Install pipenv
        run: pip install pipenv
        
      - name: Create external Docker network
        run: docker network create llm-rag-network || true
        
      - name: Build Docker image
        run: docker build -t test-image -f src/Dockerfile .

      - name: Start services
        run: docker compose -f src/docker-compose.yml up -d

      - name: Install dependencies
        run: |
          PIPENV_PIPFILE=src/Pipfile pipenv install --deploy --dev

      - name: Run tests with coverage
        run: |
          mkdir -p coverage-reports
          PIPENV_PIPFILE=src/Pipfile pipenv run pytest --cov=src --cov-report=xml:coverage-reports/coverage.xml --cov-report=html:coverage-reports/html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: coverage-reports

      - name: Tear down services
        if: always()
        run: docker compose -f src/docker-compose.yml down
